@WebApi_HostAddress = https://localhost:7289

POST {{WebApi_HostAddress}}/api/shop/create
Content-Type: application/json

{
  "Name": "Cafe Gallardo",
  "Location": "Esbjerg",
  "ShopTypeId": 3
}

###

GET {{WebApi_HostAddress}}/api/shops?pageSize=100

###

PUT {{WebApi_HostAddress}}/api/shop/edit
Content-Type: application/json

{
  "ShopId":1,
  "Name":"Poer",
  "ShopTypeId":3,
  "Location":"Nowhere"
}

###

PATCH {{WebApi_HostAddress}}/api/shop?shopId=3
Content-Type: application/json-patch+json

[
    {
        "op": "copy",
        "from": "/Name",
        "path": "/Location",
    },
    {
        "op": "replace",
        "path": "/ShopTypeId",
        "value": 1
    },
    {
        "op": "replace",
        "path": "/Name",
        "value": "Steak n mor"
    }
]

###

DELETE {{WebApi_HostAddress}}/api/shop/remove?Shopid=2
